name: Checks

on:
  push:
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/**'
    - 'LICENSE.txt'
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_common:
    name: "Check CI scripts"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: "Checking for common errors in build, deployment, and CI."
      run: ./scripts/check-common.sh

  check_PR_TODOs:
    name: "Check PR-TODOs"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: "Checking for open PR-related TODO items"
      run: ./scripts/check-pr-todos.sh

  check_clang_format:
    name: "Check C++ style"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: 'src'
        exclude-regex: 'crispy/sse2neon.h'

  check_clang_tidy:
    name: "Check C++ clang-tidy"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Updating APT package database
      run: sudo apt -q update && sudo apt upgrade -y
    - name: Installing xmllint for ci-set-vars
      run: sudo apt -qy install libxml2-utils
    - name: set environment variables
      id: set_vars
      run: ./scripts/ci-set-vars.sh
      env:
        REPOSITORY: ${{ github.event.repository.name }}
    - name: "install dependencies"
      run: sudo ./scripts/install-deps.sh
    - name: "Post-fix embedded dependency permissions."
      run: sudo find _deps/sources -exec chown $UID {} \;
    - uses: HorstBaerbel/action-clang-tidy@1.2
      name: Run clang-tidy
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: ''
        extensions: 'cpp,h,hpp'
        cmakeoptions: ''

  editorconfig:
    name: "Check editorconfig"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
